### ISSUE TITLE
Suggestion: Make it possible to pick outgroup for RAxML run

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [molbiodiv/bcgTree#22]
Just as a suggestion: How about adding the option to define which proteome is the outgroup?

Not very important, might be handy anyway...

**Comment by iimog** [comment]
I agree that this can be useful. `RAxML` as well as the other tools have a lot of options and `bcgTree` does not give much flexibility in changing them. So I am considering a generic way to pass arbitrary options to the external tools. Something like `--raxml-option "outGroupName=Rat"` which would result in a `raxml` command like `raxml --outGroupName Rat`. As your request does not seem to be urgent I will work on the generic solution in the next days. Let me know if you can't wait so long.

**Comment by MichaelsGITIGIT** [comment]
Generic solution sounds great!

Nope, it is not urgent. I can always rearange the tree later after having run bcgTree.
I only have to find a way to reroot the newick which keeps the bootstrap values all I tried so far kick the bootstrap values. But I guess there should be some tool...

**Comment by iimog** [comment]
Generic solution is implemented as follows:
There is a new option `--raxml-args` this option takes an arbitrary string as argument that is appended as is to the `raxml` command.

So you can use it like this: `bcgTree.pl [...] --raxml-args "-o Rat --mesquite"`.

This way raxml is called like: `raxml [...] -o Rat --mesquite`

So you should add quotes but they are stripped for the actual command. In the GUI this option is also available under Advanced options. Here you should not add quotes as they are added automatically.

**Comment by MichaelsGITIGIT** [comment]
Great! Many thanks!
