### ISSUE TITLE
 /bin/tar: Argument list too long

### ISSUE THREAD

**Issue by selenocysteine** [molbiodiv/bcgTree#31]
Hi,
thanks for the work, the software is a good wrapper and I am using it to build trees of huge datasets (5k+ bacterial species). An issue I have encountered in Linux (no idea if it applied to other OS's) is that if the list of --proteome items is too long, it reaches the size limit for terminal arguments (visible with the command getconf ARG_MAX) and you get an error "/bin/tar: Argument list too long". 
To overcome this I think it would be useful if, instead of through command line arguments, the list of proteomes could be inputted as a file. 
Thanks again!

**Comment by chiras** [comment]
Dear @selenocysteine,

glad to hear you like the tool. Have you tried to provide a file with the  [@configfile] option? I am not sure whether this resolves your issue. If not, maybe @iimog can help more.

Best, Alex

**Comment by selenocysteine** [comment]
Hi Alex, thanks for your fast answer. It works if you use a file inputted with configfile!

**Comment by chiras** [comment]
Glad to hear, I will close the issue then!
