### ISSUE TITLE
apply for instructions for bcgTree with Figures 

### ISSUE THREAD

**Issue by xmliuyang** [molbiodiv/bcgTree#40]
Dear sir,

I am very intersted in bcgTree, but I am not familiar with GUI. would you please sent me the detail information of installing, data, external programs and usage? my email: liuyang19860613@126.com. I will appreciate it if i get the pipeline with detailed instructions. Thank you very much.

best,

Yang Liu

**Comment by iimog** [comment]
Dear Yang Liu,

I'm not quite sure what you are asking. Instructions on how to use bcgTree can be found in the README: https://github.com/molbiodiv/bcgTree/README.org If you still have specific questions feel free to ask them but general instructions are there. Also the program (perl script and java jar) as well as source code are available here via GitHub.
Let me know if you have any specific problems I can assist you with.

Best,
Markus
