### ISSUE TITLE
option for an outgroup

### ISSUE THREAD

**Issue by jianshu93** [molbiodiv/bcgTree#41]
Hi~Raxml can build a tree using a outgroup as reference (one of the input proteome provided). Can you please also add the option? Otherwise I have to re run the Raxml step separately using intermediate alignment fa file. Thanks

**Comment by chiras** [comment]
Hi @jianshu93 

you can pass any argument to RaxML already:

`    
[--raxml-args "<ARGS>"]
        Arbitrary options to pass through to RAxML. The ARGS part should be
        in quotes and is appended to the RAxML command as given.
`

I hope this helps, best
Alex
