### ISSUE TITLE
multipleprocess implementation of hmm search

### ISSUE THREAD

**Issue by jianshu93** [molbiodiv/bcgTree#42]
When I have a big collection of genome (one thousand for example), hmmsearch one by one is really slow.  Any possibility to make it multiprocess?

**Comment by iimog** [comment]
Unfortunately, the way it is implemented right now, this is not possible. It loops over all proteomes in a `foreach` which is not parallel in perl by default: https://github.com/molbiodiv/bcgTree/blob/06cbbe11384293ff4a561e18cbcdfc213f7851bb/lib/bcgTree.pm#L114

There might be a possibility to get this functionality using a package like: https://metacpan.org/pod/Parallel::Loops but it certainly needs some adjustments. `hmmsearch` itself uses multiple threads by default but I understand that in a scenario with this many genomes further parallelization is desirable.

**Comment by jianshu93** [comment]
Thanks for the quick response. Can you also please add an mafft option? I tried a 1200 genome collection and the alignment is slow if using muscle. I think this will be very easy to implement and we can use more threads for alignment.

Thanks,

Jianshu

**Comment by iimog** [comment]
Hi Jianshu, thanks for the suggestion. I'd be happy to implement that. Just to clarify, you would just replace the `muscle` calls with `mafft` calls. Would you still use `Gblocks` afterwards? Would something else need adjustment? Is the output format of mafft the same as that of muscle?

**Comment by chiras** [comment]
Hey Jianshu, all good suggestions. Be aware with mafft that it might result in different outcomes, we have not benchmarked it with that. It should be doable to replace it, as Markus suggested, but we can at the moment not say whether this will yield similar results and may need further parameter adjustments. 

As for multithreading: This can be tricky depending on which multithreading architecture is available. The individual parts themselves are multithreaded already, but are called serialised as Markus said as well. What we may implement would also be `--continue` option, where bcgtree can define checkpoints. You could then parallelize the hmms yourself and afterwards continue bcgtree. This is just an idea, Markus and me can discuss it early November.

**Comment by jianshu93** [comment]
I agree but iqtree seems to be a better option to reduce computational time. I am also trying PhyloPhlan3. It uses trimAl and iqtree2 but I think the idea is very similar（BTW I am actually using HPC and I will not worry about time，a few month is acceptable）
